// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/threat_intelligence.proto

package threatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 威脅情報資料結構
type ThreatIntelligence struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	FileHash        string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ThreatType      string                 `protobuf:"bytes,6,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Severity        string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags            []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfidenceScore int32                  `protobuf:"varint,11,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Source          string                 `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	FirstSeen       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsActive        bool                   `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	RiskScore       string                 `protobuf:"bytes,18,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreatIntelligence) Reset() {
	*x = ThreatIntelligence{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatIntelligence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatIntelligence) ProtoMessage() {}

func (x *ThreatIntelligence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatIntelligence.ProtoReflect.Descriptor instead.
func (*ThreatIntelligence) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *ThreatIntelligence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreatIntelligence) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ThreatIntelligence) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ThreatIntelligence) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ThreatIntelligence) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *ThreatIntelligence) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *ThreatIntelligence) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ThreatIntelligence) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ThreatIntelligence) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ThreatIntelligence) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ThreatIntelligence) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ThreatIntelligence) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ThreatIntelligence) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *ThreatIntelligence) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ThreatIntelligence) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThreatIntelligence) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ThreatIntelligence) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ThreatIntelligence) GetRiskScore() string {
	if x != nil {
		return x.RiskScore
	}
	return ""
}

// 分頁資訊
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrevious   bool                   `protobuf:"varint,6,opt,name=has_previous,json=hasPrevious,proto3" json:"has_previous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Pagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *Pagination) GetHasPrevious() bool {
	if x != nil {
		return x.HasPrevious
	}
	return false
}

// 請求訊息
type GetThreatIntelligenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatIntelligenceRequest) Reset() {
	*x = GetThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatIntelligenceRequest) ProtoMessage() {}

func (x *GetThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*GetThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *GetThreatIntelligenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ThreatIntelligence    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatIntelligenceResponse) Reset() {
	*x = GetThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatIntelligenceResponse) ProtoMessage() {}

func (x *GetThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*GetThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *GetThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetThreatIntelligenceResponse) GetData() *ThreatIntelligence {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type ListThreatIntelligenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ThreatType    string                 `protobuf:"bytes,3,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreatIntelligenceRequest) Reset() {
	*x = ListThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreatIntelligenceRequest) ProtoMessage() {}

func (x *ListThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*ListThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *ListThreatIntelligenceRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListThreatIntelligenceRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListThreatIntelligenceRequest) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *ListThreatIntelligenceRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ListThreatIntelligenceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListThreatIntelligenceRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListThreatIntelligenceRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *ListThreatIntelligenceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Threats       []*ThreatIntelligence  `protobuf:"bytes,3,rep,name=threats,proto3" json:"threats,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreatIntelligenceResponse) Reset() {
	*x = ListThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreatIntelligenceResponse) ProtoMessage() {}

func (x *ListThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*ListThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *ListThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListThreatIntelligenceResponse) GetThreats() []*ThreatIntelligence {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *ListThreatIntelligenceResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type CreateThreatIntelligenceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IpAddress       string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Domain          string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FileHash        string                 `protobuf:"bytes,4,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ThreatType      string                 `protobuf:"bytes,5,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Severity        string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Tags            []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfidenceScore int32                  `protobuf:"varint,10,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Source          string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	FirstSeen       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateThreatIntelligenceRequest) Reset() {
	*x = CreateThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreatIntelligenceRequest) ProtoMessage() {}

func (x *CreateThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*CreateThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *CreateThreatIntelligenceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateThreatIntelligenceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateThreatIntelligenceRequest) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *CreateThreatIntelligenceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateThreatIntelligenceRequest) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *CreateThreatIntelligenceRequest) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CreateThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ThreatIntelligence    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateThreatIntelligenceResponse) Reset() {
	*x = CreateThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreatIntelligenceResponse) ProtoMessage() {}

func (x *CreateThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*CreateThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *CreateThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateThreatIntelligenceResponse) GetData() *ThreatIntelligence {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type UpdateThreatIntelligenceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress       string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Domain          string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	FileHash        string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ThreatType      string                 `protobuf:"bytes,6,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Severity        string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags            []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfidenceScore int32                  `protobuf:"varint,11,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Source          string                 `protobuf:"bytes,12,opt,name=source,proto3" json:"source,omitempty"`
	FirstSeen       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IsActive        bool                   `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateThreatIntelligenceRequest) Reset() {
	*x = UpdateThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThreatIntelligenceRequest) ProtoMessage() {}

func (x *UpdateThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*UpdateThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateThreatIntelligenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateThreatIntelligenceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateThreatIntelligenceRequest) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *UpdateThreatIntelligenceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateThreatIntelligenceRequest) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *UpdateThreatIntelligenceRequest) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *UpdateThreatIntelligenceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ThreatIntelligence    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThreatIntelligenceResponse) Reset() {
	*x = UpdateThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThreatIntelligenceResponse) ProtoMessage() {}

func (x *UpdateThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*UpdateThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateThreatIntelligenceResponse) GetData() *ThreatIntelligence {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type DeleteThreatIntelligenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreatIntelligenceRequest) Reset() {
	*x = DeleteThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreatIntelligenceRequest) ProtoMessage() {}

func (x *DeleteThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteThreatIntelligenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreatIntelligenceResponse) Reset() {
	*x = DeleteThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreatIntelligenceResponse) ProtoMessage() {}

func (x *DeleteThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*DeleteThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type SearchThreatIntelligenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	ThreatType    string                 `protobuf:"bytes,4,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreatIntelligenceRequest) Reset() {
	*x = SearchThreatIntelligenceRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreatIntelligenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreatIntelligenceRequest) ProtoMessage() {}

func (x *SearchThreatIntelligenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreatIntelligenceRequest.ProtoReflect.Descriptor instead.
func (*SearchThreatIntelligenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{12}
}

func (x *SearchThreatIntelligenceRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchThreatIntelligenceRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchThreatIntelligenceRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchThreatIntelligenceRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type SearchThreatIntelligenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Threats       []*ThreatIntelligence  `protobuf:"bytes,3,rep,name=threats,proto3" json:"threats,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreatIntelligenceResponse) Reset() {
	*x = SearchThreatIntelligenceResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreatIntelligenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreatIntelligenceResponse) ProtoMessage() {}

func (x *SearchThreatIntelligenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreatIntelligenceResponse.ProtoReflect.Descriptor instead.
func (*SearchThreatIntelligenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{13}
}

func (x *SearchThreatIntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchThreatIntelligenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchThreatIntelligenceResponse) GetThreats() []*ThreatIntelligence {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *SearchThreatIntelligenceResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchThreatIntelligenceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type GetThreatStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"` // daily, weekly, monthly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatStatisticsRequest) Reset() {
	*x = GetThreatStatisticsRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatStatisticsRequest) ProtoMessage() {}

func (x *GetThreatStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetThreatStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{14}
}

func (x *GetThreatStatisticsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetThreatStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ThreatStatistics      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreatStatisticsResponse) Reset() {
	*x = GetThreatStatisticsResponse{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreatStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreatStatisticsResponse) ProtoMessage() {}

func (x *GetThreatStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreatStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetThreatStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{15}
}

func (x *GetThreatStatisticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetThreatStatisticsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetThreatStatisticsResponse) GetData() *ThreatStatistics {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetThreatStatisticsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type ThreatStatistics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalThreats      int64                  `protobuf:"varint,1,opt,name=total_threats,json=totalThreats,proto3" json:"total_threats,omitempty"`
	ActiveThreats     int64                  `protobuf:"varint,2,opt,name=active_threats,json=activeThreats,proto3" json:"active_threats,omitempty"`
	HighRiskThreats   int64                  `protobuf:"varint,3,opt,name=high_risk_threats,json=highRiskThreats,proto3" json:"high_risk_threats,omitempty"`
	MediumRiskThreats int64                  `protobuf:"varint,4,opt,name=medium_risk_threats,json=mediumRiskThreats,proto3" json:"medium_risk_threats,omitempty"`
	LowRiskThreats    int64                  `protobuf:"varint,5,opt,name=low_risk_threats,json=lowRiskThreats,proto3" json:"low_risk_threats,omitempty"`
	ThreatTypes       map[string]int64       `protobuf:"bytes,6,rep,name=threat_types,json=threatTypes,proto3" json:"threat_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sources           map[string]int64       `protobuf:"bytes,7,rep,name=sources,proto3" json:"sources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DailyStats        []*DailyStats          `protobuf:"bytes,8,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThreatStatistics) Reset() {
	*x = ThreatStatistics{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatStatistics) ProtoMessage() {}

func (x *ThreatStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatStatistics.ProtoReflect.Descriptor instead.
func (*ThreatStatistics) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{16}
}

func (x *ThreatStatistics) GetTotalThreats() int64 {
	if x != nil {
		return x.TotalThreats
	}
	return 0
}

func (x *ThreatStatistics) GetActiveThreats() int64 {
	if x != nil {
		return x.ActiveThreats
	}
	return 0
}

func (x *ThreatStatistics) GetHighRiskThreats() int64 {
	if x != nil {
		return x.HighRiskThreats
	}
	return 0
}

func (x *ThreatStatistics) GetMediumRiskThreats() int64 {
	if x != nil {
		return x.MediumRiskThreats
	}
	return 0
}

func (x *ThreatStatistics) GetLowRiskThreats() int64 {
	if x != nil {
		return x.LowRiskThreats
	}
	return 0
}

func (x *ThreatStatistics) GetThreatTypes() map[string]int64 {
	if x != nil {
		return x.ThreatTypes
	}
	return nil
}

func (x *ThreatStatistics) GetSources() map[string]int64 {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ThreatStatistics) GetDailyStats() []*DailyStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type DailyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HighRisk      int64                  `protobuf:"varint,3,opt,name=high_risk,json=highRisk,proto3" json:"high_risk,omitempty"`
	MediumRisk    int64                  `protobuf:"varint,4,opt,name=medium_risk,json=mediumRisk,proto3" json:"medium_risk,omitempty"`
	LowRisk       int64                  `protobuf:"varint,5,opt,name=low_risk,json=lowRisk,proto3" json:"low_risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{17}
}

func (x *DailyStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStats) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DailyStats) GetHighRisk() int64 {
	if x != nil {
		return x.HighRisk
	}
	return 0
}

func (x *DailyStats) GetMediumRisk() int64 {
	if x != nil {
		return x.MediumRisk
	}
	return 0
}

func (x *DailyStats) GetLowRisk() int64 {
	if x != nil {
		return x.LowRisk
	}
	return 0
}

type SubscribeThreatsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ThreatTypes        []string               `protobuf:"bytes,1,rep,name=threat_types,json=threatTypes,proto3" json:"threat_types,omitempty"`
	Severities         []string               `protobuf:"bytes,2,rep,name=severities,proto3" json:"severities,omitempty"`
	MinConfidenceScore int32                  `protobuf:"varint,3,opt,name=min_confidence_score,json=minConfidenceScore,proto3" json:"min_confidence_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubscribeThreatsRequest) Reset() {
	*x = SubscribeThreatsRequest{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeThreatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeThreatsRequest) ProtoMessage() {}

func (x *SubscribeThreatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeThreatsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeThreatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeThreatsRequest) GetThreatTypes() []string {
	if x != nil {
		return x.ThreatTypes
	}
	return nil
}

func (x *SubscribeThreatsRequest) GetSeverities() []string {
	if x != nil {
		return x.Severities
	}
	return nil
}

func (x *SubscribeThreatsRequest) GetMinConfidenceScore() int32 {
	if x != nil {
		return x.MinConfidenceScore
	}
	return 0
}

type ThreatNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // created, updated, deleted
	Threat         *ThreatIntelligence    `protobuf:"bytes,3,opt,name=threat,proto3" json:"threat,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreatNotification) Reset() {
	*x = ThreatNotification{}
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatNotification) ProtoMessage() {}

func (x *ThreatNotification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_threat_intelligence_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatNotification.ProtoReflect.Descriptor instead.
func (*ThreatNotification) Descriptor() ([]byte, []int) {
	return file_api_proto_threat_intelligence_proto_rawDescGZIP(), []int{19}
}

func (x *ThreatNotification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *ThreatNotification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ThreatNotification) GetThreat() *ThreatIntelligence {
	if x != nil {
		return x.Threat
	}
	return nil
}

func (x *ThreatNotification) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ThreatNotification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_threat_intelligence_proto protoreflect.FileDescriptor

const file_api_proto_threat_intelligence_proto_rawDesc = "" +
	"\n" +
	"#api/proto/threat_intelligence.proto\x12\x13threat_intelligence\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x05\n" +
	"\x12ThreatIntelligence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12\x1f\n" +
	"\vthreat_type\x18\x06 \x01(\tR\n" +
	"threatType\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12Q\n" +
	"\bmetadata\x18\n" +
	" \x03(\v25.threat_intelligence.ThreatIntelligence.MetadataEntryR\bmetadata\x12)\n" +
	"\x10confidence_score\x18\v \x01(\x05R\x0fconfidenceScore\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x129\n" +
	"\n" +
	"first_seen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\x11 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x12 \x01(\tR\triskScore\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\n" +
	"Pagination\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x03R\ftotalRecords\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12!\n" +
	"\fhas_previous\x18\x06 \x01(\bR\vhasPrevious\".\n" +
	"\x1cGetThreatIntelligenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaf\x01\n" +
	"\x1dGetThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2'.threat_intelligence.ThreatIntelligenceR\x04data\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xfa\x01\n" +
	"\x1dListThreatIntelligenceRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vthreat_type\x18\x03 \x01(\tR\n" +
	"threatType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\tR\tsortOrder\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\xf7\x01\n" +
	"\x1eListThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\athreats\x18\x03 \x03(\v2'.threat_intelligence.ThreatIntelligenceR\athreats\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.threat_intelligence.PaginationR\n" +
	"pagination\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\"\xce\x04\n" +
	"\x1fCreateThreatIntelligenceRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_hash\x18\x04 \x01(\tR\bfileHash\x12\x1f\n" +
	"\vthreat_type\x18\x05 \x01(\tR\n" +
	"threatType\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12^\n" +
	"\bmetadata\x18\t \x03(\v2B.threat_intelligence.CreateThreatIntelligenceRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10confidence_score\x18\n" +
	" \x01(\x05R\x0fconfidenceScore\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x129\n" +
	"\n" +
	"first_seen\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	" CreateThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2'.threat_intelligence.ThreatIntelligenceR\x04data\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xfb\x04\n" +
	"\x1fUpdateThreatIntelligenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12\x1f\n" +
	"\vthreat_type\x18\x06 \x01(\tR\n" +
	"threatType\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12^\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2B.threat_intelligence.UpdateThreatIntelligenceRequest.MetadataEntryR\bmetadata\x12)\n" +
	"\x10confidence_score\x18\v \x01(\x05R\x0fconfidenceScore\x12\x16\n" +
	"\x06source\x18\f \x01(\tR\x06source\x129\n" +
	"\n" +
	"first_seen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	" UpdateThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x03 \x01(\v2'.threat_intelligence.ThreatIntelligenceR\x04data\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"1\n" +
	"\x1fDeleteThreatIntelligenceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	" DeleteThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\x94\x02\n" +
	"\x1fSearchThreatIntelligenceRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1f\n" +
	"\vthreat_type\x18\x04 \x01(\tR\n" +
	"threatType\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\tR\tsortOrder\"\xf9\x01\n" +
	" SearchThreatIntelligenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\athreats\x18\x03 \x03(\v2'.threat_intelligence.ThreatIntelligenceR\athreats\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.threat_intelligence.PaginationR\n" +
	"pagination\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\"4\n" +
	"\x1aGetThreatStatisticsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"\xab\x01\n" +
	"\x1bGetThreatStatisticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.threat_intelligence.ThreatStatisticsR\x04data\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xcb\x04\n" +
	"\x10ThreatStatistics\x12#\n" +
	"\rtotal_threats\x18\x01 \x01(\x03R\ftotalThreats\x12%\n" +
	"\x0eactive_threats\x18\x02 \x01(\x03R\ractiveThreats\x12*\n" +
	"\x11high_risk_threats\x18\x03 \x01(\x03R\x0fhighRiskThreats\x12.\n" +
	"\x13medium_risk_threats\x18\x04 \x01(\x03R\x11mediumRiskThreats\x12(\n" +
	"\x10low_risk_threats\x18\x05 \x01(\x03R\x0elowRiskThreats\x12Y\n" +
	"\fthreat_types\x18\x06 \x03(\v26.threat_intelligence.ThreatStatistics.ThreatTypesEntryR\vthreatTypes\x12L\n" +
	"\asources\x18\a \x03(\v22.threat_intelligence.ThreatStatistics.SourcesEntryR\asources\x12@\n" +
	"\vdaily_stats\x18\b \x03(\v2\x1f.threat_intelligence.DailyStatsR\n" +
	"dailyStats\x1a>\n" +
	"\x10ThreatTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a:\n" +
	"\fSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x8f\x01\n" +
	"\n" +
	"DailyStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x1b\n" +
	"\thigh_risk\x18\x03 \x01(\x03R\bhighRisk\x12\x1f\n" +
	"\vmedium_risk\x18\x04 \x01(\x03R\n" +
	"mediumRisk\x12\x19\n" +
	"\blow_risk\x18\x05 \x01(\x03R\alowRisk\"\x8e\x01\n" +
	"\x17SubscribeThreatsRequest\x12!\n" +
	"\fthreat_types\x18\x01 \x03(\tR\vthreatTypes\x12\x1e\n" +
	"\n" +
	"severities\x18\x02 \x03(\tR\n" +
	"severities\x120\n" +
	"\x14min_confidence_score\x18\x03 \x01(\x05R\x12minConfidenceScore\"\xdc\x02\n" +
	"\x12ThreatNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12?\n" +
	"\x06threat\x18\x03 \x01(\v2'.threat_intelligence.ThreatIntelligenceR\x06threat\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12Q\n" +
	"\bmetadata\x18\x05 \x03(\v25.threat_intelligence.ThreatNotification.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xae\b\n" +
	"\x19ThreatIntelligenceService\x12~\n" +
	"\x15GetThreatIntelligence\x121.threat_intelligence.GetThreatIntelligenceRequest\x1a2.threat_intelligence.GetThreatIntelligenceResponse\x12\x81\x01\n" +
	"\x16ListThreatIntelligence\x122.threat_intelligence.ListThreatIntelligenceRequest\x1a3.threat_intelligence.ListThreatIntelligenceResponse\x12\x87\x01\n" +
	"\x18CreateThreatIntelligence\x124.threat_intelligence.CreateThreatIntelligenceRequest\x1a5.threat_intelligence.CreateThreatIntelligenceResponse\x12\x87\x01\n" +
	"\x18UpdateThreatIntelligence\x124.threat_intelligence.UpdateThreatIntelligenceRequest\x1a5.threat_intelligence.UpdateThreatIntelligenceResponse\x12\x87\x01\n" +
	"\x18DeleteThreatIntelligence\x124.threat_intelligence.DeleteThreatIntelligenceRequest\x1a5.threat_intelligence.DeleteThreatIntelligenceResponse\x12\x87\x01\n" +
	"\x18SearchThreatIntelligence\x124.threat_intelligence.SearchThreatIntelligenceRequest\x1a5.threat_intelligence.SearchThreatIntelligenceResponse\x12x\n" +
	"\x13GetThreatStatistics\x12/.threat_intelligence.GetThreatStatisticsRequest\x1a0.threat_intelligence.GetThreatStatisticsResponse\x12k\n" +
	"\x10SubscribeThreats\x12,.threat_intelligence.SubscribeThreatsRequest\x1a'.threat_intelligence.ThreatNotification0\x01BYZWgithub.com/lipeichen/Ultimate-Security-Intelligence-Platform/backend/api/proto;threatpbb\x06proto3"

var (
	file_api_proto_threat_intelligence_proto_rawDescOnce sync.Once
	file_api_proto_threat_intelligence_proto_rawDescData []byte
)

func file_api_proto_threat_intelligence_proto_rawDescGZIP() []byte {
	file_api_proto_threat_intelligence_proto_rawDescOnce.Do(func() {
		file_api_proto_threat_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_threat_intelligence_proto_rawDesc), len(file_api_proto_threat_intelligence_proto_rawDesc)))
	})
	return file_api_proto_threat_intelligence_proto_rawDescData
}

var file_api_proto_threat_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_proto_threat_intelligence_proto_goTypes = []any{
	(*ThreatIntelligence)(nil),               // 0: threat_intelligence.ThreatIntelligence
	(*Pagination)(nil),                       // 1: threat_intelligence.Pagination
	(*GetThreatIntelligenceRequest)(nil),     // 2: threat_intelligence.GetThreatIntelligenceRequest
	(*GetThreatIntelligenceResponse)(nil),    // 3: threat_intelligence.GetThreatIntelligenceResponse
	(*ListThreatIntelligenceRequest)(nil),    // 4: threat_intelligence.ListThreatIntelligenceRequest
	(*ListThreatIntelligenceResponse)(nil),   // 5: threat_intelligence.ListThreatIntelligenceResponse
	(*CreateThreatIntelligenceRequest)(nil),  // 6: threat_intelligence.CreateThreatIntelligenceRequest
	(*CreateThreatIntelligenceResponse)(nil), // 7: threat_intelligence.CreateThreatIntelligenceResponse
	(*UpdateThreatIntelligenceRequest)(nil),  // 8: threat_intelligence.UpdateThreatIntelligenceRequest
	(*UpdateThreatIntelligenceResponse)(nil), // 9: threat_intelligence.UpdateThreatIntelligenceResponse
	(*DeleteThreatIntelligenceRequest)(nil),  // 10: threat_intelligence.DeleteThreatIntelligenceRequest
	(*DeleteThreatIntelligenceResponse)(nil), // 11: threat_intelligence.DeleteThreatIntelligenceResponse
	(*SearchThreatIntelligenceRequest)(nil),  // 12: threat_intelligence.SearchThreatIntelligenceRequest
	(*SearchThreatIntelligenceResponse)(nil), // 13: threat_intelligence.SearchThreatIntelligenceResponse
	(*GetThreatStatisticsRequest)(nil),       // 14: threat_intelligence.GetThreatStatisticsRequest
	(*GetThreatStatisticsResponse)(nil),      // 15: threat_intelligence.GetThreatStatisticsResponse
	(*ThreatStatistics)(nil),                 // 16: threat_intelligence.ThreatStatistics
	(*DailyStats)(nil),                       // 17: threat_intelligence.DailyStats
	(*SubscribeThreatsRequest)(nil),          // 18: threat_intelligence.SubscribeThreatsRequest
	(*ThreatNotification)(nil),               // 19: threat_intelligence.ThreatNotification
	nil,                                      // 20: threat_intelligence.ThreatIntelligence.MetadataEntry
	nil,                                      // 21: threat_intelligence.CreateThreatIntelligenceRequest.MetadataEntry
	nil,                                      // 22: threat_intelligence.UpdateThreatIntelligenceRequest.MetadataEntry
	nil,                                      // 23: threat_intelligence.ThreatStatistics.ThreatTypesEntry
	nil,                                      // 24: threat_intelligence.ThreatStatistics.SourcesEntry
	nil,                                      // 25: threat_intelligence.ThreatNotification.MetadataEntry
	(*timestamppb.Timestamp)(nil),            // 26: google.protobuf.Timestamp
}
var file_api_proto_threat_intelligence_proto_depIdxs = []int32{
	20, // 0: threat_intelligence.ThreatIntelligence.metadata:type_name -> threat_intelligence.ThreatIntelligence.MetadataEntry
	26, // 1: threat_intelligence.ThreatIntelligence.first_seen:type_name -> google.protobuf.Timestamp
	26, // 2: threat_intelligence.ThreatIntelligence.last_seen:type_name -> google.protobuf.Timestamp
	26, // 3: threat_intelligence.ThreatIntelligence.created_at:type_name -> google.protobuf.Timestamp
	26, // 4: threat_intelligence.ThreatIntelligence.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: threat_intelligence.GetThreatIntelligenceResponse.data:type_name -> threat_intelligence.ThreatIntelligence
	0,  // 6: threat_intelligence.ListThreatIntelligenceResponse.threats:type_name -> threat_intelligence.ThreatIntelligence
	1,  // 7: threat_intelligence.ListThreatIntelligenceResponse.pagination:type_name -> threat_intelligence.Pagination
	21, // 8: threat_intelligence.CreateThreatIntelligenceRequest.metadata:type_name -> threat_intelligence.CreateThreatIntelligenceRequest.MetadataEntry
	26, // 9: threat_intelligence.CreateThreatIntelligenceRequest.first_seen:type_name -> google.protobuf.Timestamp
	26, // 10: threat_intelligence.CreateThreatIntelligenceRequest.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 11: threat_intelligence.CreateThreatIntelligenceResponse.data:type_name -> threat_intelligence.ThreatIntelligence
	22, // 12: threat_intelligence.UpdateThreatIntelligenceRequest.metadata:type_name -> threat_intelligence.UpdateThreatIntelligenceRequest.MetadataEntry
	26, // 13: threat_intelligence.UpdateThreatIntelligenceRequest.first_seen:type_name -> google.protobuf.Timestamp
	26, // 14: threat_intelligence.UpdateThreatIntelligenceRequest.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 15: threat_intelligence.UpdateThreatIntelligenceResponse.data:type_name -> threat_intelligence.ThreatIntelligence
	0,  // 16: threat_intelligence.SearchThreatIntelligenceResponse.threats:type_name -> threat_intelligence.ThreatIntelligence
	1,  // 17: threat_intelligence.SearchThreatIntelligenceResponse.pagination:type_name -> threat_intelligence.Pagination
	16, // 18: threat_intelligence.GetThreatStatisticsResponse.data:type_name -> threat_intelligence.ThreatStatistics
	23, // 19: threat_intelligence.ThreatStatistics.threat_types:type_name -> threat_intelligence.ThreatStatistics.ThreatTypesEntry
	24, // 20: threat_intelligence.ThreatStatistics.sources:type_name -> threat_intelligence.ThreatStatistics.SourcesEntry
	17, // 21: threat_intelligence.ThreatStatistics.daily_stats:type_name -> threat_intelligence.DailyStats
	0,  // 22: threat_intelligence.ThreatNotification.threat:type_name -> threat_intelligence.ThreatIntelligence
	26, // 23: threat_intelligence.ThreatNotification.timestamp:type_name -> google.protobuf.Timestamp
	25, // 24: threat_intelligence.ThreatNotification.metadata:type_name -> threat_intelligence.ThreatNotification.MetadataEntry
	2,  // 25: threat_intelligence.ThreatIntelligenceService.GetThreatIntelligence:input_type -> threat_intelligence.GetThreatIntelligenceRequest
	4,  // 26: threat_intelligence.ThreatIntelligenceService.ListThreatIntelligence:input_type -> threat_intelligence.ListThreatIntelligenceRequest
	6,  // 27: threat_intelligence.ThreatIntelligenceService.CreateThreatIntelligence:input_type -> threat_intelligence.CreateThreatIntelligenceRequest
	8,  // 28: threat_intelligence.ThreatIntelligenceService.UpdateThreatIntelligence:input_type -> threat_intelligence.UpdateThreatIntelligenceRequest
	10, // 29: threat_intelligence.ThreatIntelligenceService.DeleteThreatIntelligence:input_type -> threat_intelligence.DeleteThreatIntelligenceRequest
	12, // 30: threat_intelligence.ThreatIntelligenceService.SearchThreatIntelligence:input_type -> threat_intelligence.SearchThreatIntelligenceRequest
	14, // 31: threat_intelligence.ThreatIntelligenceService.GetThreatStatistics:input_type -> threat_intelligence.GetThreatStatisticsRequest
	18, // 32: threat_intelligence.ThreatIntelligenceService.SubscribeThreats:input_type -> threat_intelligence.SubscribeThreatsRequest
	3,  // 33: threat_intelligence.ThreatIntelligenceService.GetThreatIntelligence:output_type -> threat_intelligence.GetThreatIntelligenceResponse
	5,  // 34: threat_intelligence.ThreatIntelligenceService.ListThreatIntelligence:output_type -> threat_intelligence.ListThreatIntelligenceResponse
	7,  // 35: threat_intelligence.ThreatIntelligenceService.CreateThreatIntelligence:output_type -> threat_intelligence.CreateThreatIntelligenceResponse
	9,  // 36: threat_intelligence.ThreatIntelligenceService.UpdateThreatIntelligence:output_type -> threat_intelligence.UpdateThreatIntelligenceResponse
	11, // 37: threat_intelligence.ThreatIntelligenceService.DeleteThreatIntelligence:output_type -> threat_intelligence.DeleteThreatIntelligenceResponse
	13, // 38: threat_intelligence.ThreatIntelligenceService.SearchThreatIntelligence:output_type -> threat_intelligence.SearchThreatIntelligenceResponse
	15, // 39: threat_intelligence.ThreatIntelligenceService.GetThreatStatistics:output_type -> threat_intelligence.GetThreatStatisticsResponse
	19, // 40: threat_intelligence.ThreatIntelligenceService.SubscribeThreats:output_type -> threat_intelligence.ThreatNotification
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_threat_intelligence_proto_init() }
func file_api_proto_threat_intelligence_proto_init() {
	if File_api_proto_threat_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_threat_intelligence_proto_rawDesc), len(file_api_proto_threat_intelligence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_threat_intelligence_proto_goTypes,
		DependencyIndexes: file_api_proto_threat_intelligence_proto_depIdxs,
		MessageInfos:      file_api_proto_threat_intelligence_proto_msgTypes,
	}.Build()
	File_api_proto_threat_intelligence_proto = out.File
	file_api_proto_threat_intelligence_proto_goTypes = nil
	file_api_proto_threat_intelligence_proto_depIdxs = nil
}
