global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "security-intel-backend"
    static_configs:
      - targets: ["localhost:8080"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["localhost:5432"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["localhost:6379"]
    metrics_path: "/metrics"

  - job_name: "mosquitto"
    static_configs:
      - targets: ["localhost:1883"]
    metrics_path: "/metrics"
